### ISSUE TITLE
feat: Multiple Feature Ideas I had after playing with the tool for a minute

### ISSUE THREAD

**Issue by tdarwin** [honeycombio/loadgen#3]
## Thought I'd just load up some of the ideas we discussed in Slack so that I don't forget about them

- Add an option for interjecting a percentage of spans that would have an error field
- Being able to add custom fields and values that you want to see at X rate so that we can build refinery rules around specific span attributes
- A way to hook it up to Lambda's that could be called via the API Gateway to spin up multple loadgens generating different kind of traffic.

## Some extra ideas I thought of on top of things

These might be things we can do with running via multiple lambdas, but would be cool in the tool as well

- Outlier options - being able to add outlier traces that are generated randomly in the midst of your loadgen data.
  - span count (creating a trace with a super high span count compared to others)
  - duration (either exceptionally short duration spans or long duration spans)
  - missing parent spans or trace root spans
 - multi-service traces (maybe a list of services as the option, even better if it can be a hash with service names and weights)
 - read in a CSV or JSON or YAML or something containing a list of attributes each with a list/array of values you want to exist
 - Be able to give specific field names for extra span attribute fields but still have the tool generate values for the fields.

**Comment by MikeGoldsmith** [comment]
We believe we've added enough for now.
